name: Deploy To Production
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
on:
  workflow_run:
    workflows: [Docker Image Publish]
    types:
      - completed
jobs:
  deploy:
    runs-on: arc-runner-set-hrb
    container: ghcr.io/hacking-robots-and-beer/lifeandshell:${{ github.sha }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Deploy settings
        run: python /code/get.py 